title: "Forged In The Fires Of Recovery"
baseline: "A Personal Journey"
description: "One Young Woman's Quest To Find Herself Again"
baseurl: "/"
canonicalurl: true
theme: "hyde"
date:
  format: "j F Y"
  timezone: "Europe/Paris"
pagination:
  max: 5
  path: "page"
output:
  formats:
    netlify_redirects:
      mediatype: "text/plain"
      extension: ""
virtualpages:
  admin:
    layout: admin/index
    output: html
    title: "Content Manager (Netlify CMS)"
  _redirects:
    output: netlify_redirects
netlify:
  cms:
    path: "admin"
    version: "latest"
  identity:
    version: "v1"
